### ISSUE TITLE
Update to work with clingo-5.5.0

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingoLP#10]
@sthiele Could you add a "good first issue" here ?

**Comment by rolfmorel** [comment]
Hi Max (@MaxOstrowski) and Sven (@sthiele),

Is there any news on this?

I'm working on a project where I am using some of the Clingo 5.5 API. The project crucially depends on Clingo's background theories. I was rather disappointed to find this issue indicating that using an LIA theory is going to be problematic.

Let me know if there's anything I can do to get it working.

Best,
Rolf

**Comment by sthiele** [comment]
Hi Rolf,
the migration to clingo 5.5 is done in the branch st/port-clingo-5.5. It's currently in the testing stage. From my point of view there is not much left to be done. @wanko wanted to test some things and @rkaminsk has new deployment scripts to generate packages. If you want you can run the branch. New packages should be comming soon after summer break.

**Comment by rolfmorel** [comment]
Thanks for the quick reply, Sven!

That branch works for me, at least for the example included in the repo. I am fine with working with this development version for now, though glad to hear a new release/packaged versions aren't too far away.

I will report back here if I come across any issues.

**Comment by MaxOstrowski** [comment]
@rolfmorel Maybe you are also interested in [clingcon](https://github.com/potassco/clingcon) or [clingo-dl](https://github.com/potassco/clingo-dl) also supporting LIA (clingo-dl only partially) but being much faster.

**Comment by tortinator** [comment]
This being said, we are also always keen to get beta-testers for [clingo-lpx](https://github.com/potassco/clingo-lpx)

**Comment by rolfmorel** [comment]
> @rolfmorel Maybe you are also interested in [clingcon](https://github.com/potassco/clingcon) or [clingo-dl](https://github.com/potassco/clingo-dl) also supporting LIA (clingo-dl only partially) but being much faster.

Thanks for the suggestions, Max. I already had my prototype working with Clingo[DL], but am interested in using Clingcon as well.

Can I just check, as my understanding might well be off: the domains of variables in Clingcon are always finite, right, i.e. it implements CLP(FD)? Yet both difference logic and linear integer arithmetic have domains over all the integers. Can CLP(FD)/Clingcon still be used to soundly decide LIA problems?

> This being said, we are also always keen to get beta-testers for [clingo-lpx](https://github.com/potassco/clingo-lpx)

Thanks Torsten, that project wasn't on my radar! What is the difference between the `clingoLP` and the `clingo-lpx` projects? Both appear to implement Clingo[LP]. Is the difference that the former uses existing solvers while the later implements its own simplex solver?

**Comment by tortinator** [comment]
Exactly!

**Comment by sthiele** [comment]
> What is the difference between the `clingoLP` and the `clingo-lpx` projects? Both appear to implement Clingo[LP]. Is the difference that the former uses existing solvers while the later implements its own simplex solver?

Also clingo-lpx is using rationals rather than floats.

**Comment by MaxOstrowski** [comment]
@rolfmorel 

> Can CLP(FD)/Clingcon still be used to soundly decide LIA problems?

Yes, as long as the domains are finite and given beforehand (otherwise a min/max of -2^30/2^30 is assumed) which is the case for most problems.
