### ISSUE TITLE
Relicensing to MIT

### ISSUE THREAD

**Issue by sthiele** [potassco/clingoLP#5]
@atakemura @schellhorn 
We would like to relicense clingoLP to the more permissive MIT license and doing so would require having any past and future contributors relicense their changes under the MIT license. 
If you have contributed commits to clingoLP and are willing to relicense your commits under MIT, please comment on this issue with the following:

I, <name>, license past and future contributions to clingoLP under the MIT license.

Thanks!

**Comment by sthiele** [comment]
I, Sven Thiele, license past and future contributions to clingoLP under the MIT license.

**Comment by atakemura** [comment]
I, Akihiro Takemura, license past and future contributions to clingoLP under the MIT license.

Thanks :)

**Comment by schellhorn** [comment]
I, Sebastian Schellhorn, license past and future contributions to clingoLP under the MIT license.

**Comment by sthiele** [comment]
Thanks everyone I close this issue with merging PR #6
