### ISSUE TITLE
find out why clingo_main returns 10

### ISSUE THREAD

**Issue by sthiele** [potassco/clingoLP#7]

**Comment by MaxOstrowski** [comment]
I think (just guessing) that clasp is not conformant with linux return numbers but with SAT solvers.
This mens 10 (model found), 20 UNSAT, and some other things...

**Comment by sthiele** [comment]
Do you know if this is this somewhere documented?

**Comment by MaxOstrowski** [comment]
Couldn't find it in the user guide.
Probably @rkaminsk or @BenKaufmann know more about it.
For sat solver competitions I found this:
http://www.satcompetition.org/2004/format-solvers2004.html

**Comment by rkaminsk** [comment]
Let's not start the discussion whether such kind exit codes are good or bad. The best documentation you find probably here: https://github.com/potassco/clasp/issues/42

**Comment by sthiele** [comment]
I see thank you.
